name: Vaccine

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA'
        required: true

jobs:
  prepare_vaccine:
    name: Prepare injection artifacts
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/datadog/dd-trace-rb/dd-lib-ruby-init:${{ inputs.commit_sha }}
      options: --user root
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: vaccine
          path: /datadog-init/package

  inoculate:
    name: ${{ matrix.engine.name }} ${{ matrix.engine.version }} with ${{ matrix.command }}
    needs: prepare_vaccine
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - rails s
          - bin/rails s
          - bundle exec rails s
        engine:
          - name: ruby
            version: '3.4'
          - name: ruby
            version: '3.3'
          - name: ruby
            version: '3.2'
          - name: ruby
            version: '3.1'
          - name: ruby
            version: '3.0'
          - name: ruby
            version: '2.7'
          - name: ruby
            version: '2.6'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: vaccine
          path: vaccine
      - run: ls -Al vaccine
      - run: |
          docker build \
            --build-arg RUBY_BASE_IMAGE=${{ matrix.engine.name }}:${{ matrix.engine.version }} \
            -t patient:${{ matrix.engine.name }}-${{ matrix.engine.version }} \
            --file src/Dockerfile \
            src
      - run: |
          docker run -d \
            --name inoculation \
            -e RUBYOPT=-r/vaccine/host_inject \
            -e DD_TRACE_DEBUG=true \
            -v $(pwd)/vaccine:/vaccine \
            -p 3000:3000 \
            patient:${{ matrix.engine.name }}-${{ matrix.engine.version }} \
            "${{ matrix.command }} -b 0.0.0.0"
      - run: sleep 10
      - run: docker logs inoculation
      - run: curl -v --retry 10 -f --retry-all-errors --retry-delay 5 -s -o /dev/null http://localhost:3000
      - run: docker logs inoculation
